#
# Jekyll serve with --drafts for developing
#
version: '2'
services:

  jekyll:
    image: benizar/jekyll #Image from Dockerhub
    container_name: benizar_jekyll
    ports:
      - 4000:4000
    volumes:
      - .:/home # Your sources will be in the container's home

    command: bundle exec jekyll serve --watch --incremental --drafts
