#
# Jekyll build without --drafts for deploying on github
#
version: '2'
services:
  jekyll:
    restart: always
    # comment on build if want to use the dockerhub build
    build:
      context: .
      dockerfile: Dockerfile
    image: benizar/jekyll
    container_name: benizar_jekyll
    command: bash -c "bundle install && jekyll build"
    ports:
        - 4000:4000
    volumes:
        - .:/srv/jekyll
